apply plugin: 'com.android.application'

def keystoreProperties = new Properties()
def isGithubActions = System.getenv("GITHUB_ACTIONS") == "true"
def githubBuildNumber = System.getenv("GITHUB_RUN_NUMBER")
def keystorePropertiesFile = rootProject.file('keystore.properties')

if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    defaultConfig {
        applicationId "com.pg.mikszo.friendlyletters"
        minSdkVersion 16
        compileSdkVersion = 36
        targetSdkVersion 36
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        def majorCodeEnv = System.getenv("MAJOR_COUNTER") ? System.getenv("MAJOR_COUNTER").toInteger() : 1
        def minorCodeEnv = System.getenv("MINOR_COUNTER") ? System.getenv("MINOR_COUNTER").toInteger() : 0
        def patchCodeEnv = System.getenv("PATCH_COUNTER") ? System.getenv("PATCH_COUNTER").toInteger() : 1

        versionCode isGithubActions ? (githubBuildNumber ? githubBuildNumber.toInteger() : 1) : patchCodeEnv
        versionName "${majorCodeEnv}.${minorCodeEnv}.${patchCodeEnv}"
    }
    signingConfigs {
        release {
            def keystorePath = isGithubActions ? System.getenv("KEYSTORE_PATH") : keystoreProperties.getProperty("KEYSTORE_PATH")
            storeFile keystorePath ? file(keystorePath) : null
            storePassword isGithubActions ? System.getenv("KEYSTORE_PASSWORD") : keystoreProperties.getProperty("KEYSTORE_PASSWORD")
            keyAlias isGithubActions ? System.getenv("KEY_ALIAS") : keystoreProperties.getProperty("KEY_ALIAS")
            keyPassword isGithubActions ? System.getenv("KEY_PASSWORD") : keystoreProperties.getProperty("KEY_PASSWORD")
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'com.pg.mikszo.friendlyletters'
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.google.code.gson:gson:2.8.5'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    // https://square.github.io/picasso/
    implementation 'com.squareup.picasso:picasso:2.71828'

    // https://github.com/grantland/android-autofittextview
    implementation 'me.grantland:autofittextview:0.2.1'
}
